
version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - back-tier
  frontend:
    image: node
    volumes:
     - ./frontend:/code
    networks:
      - back-tier
    working_dir: /code/
    command: ./command.sh
  nginx:
    networks:
      - back-tier
    ports:
      - 80:80
    image: nginx
    volumes:
     - ./nginx/dev:/etc/nginx/conf.d
     - static:/static
  web:
    build: ./web
    volumes:
      - ./web:/code
      - static:/static
    networks:
      - back-tier

volumes:
  pg-data:
    driver: local
  static:
    driver: local

networks:
  back-tier:
    driver: bridge
